import { jsPDF } from 'jspdf'

function safeFilename(value = 'cirilo-note') {
  return (
    String(value)
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-zA-Z0-9-_ ]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .toLowerCase() || 'cirilo-note'
  )
}

async function loadImageAsDataUrl(src) {
  const response = await fetch(src)

  if (!response.ok) {
    throw new Error(`Could not load image: ${src}`)
  }

  const blob = await response.blob()

  return new Promise((resolve, reject) => {
    const reader = new FileReader()

    reader.onload = () => resolve(reader.result)
    reader.onerror = reject

    reader.readAsDataURL(blob)
  })
}

function getUniverseStyle(universe) {
  const styles = {
    personal: {
      label: 'PERSONAL',
      accent: [47, 128, 237],
      soft: [242, 247, 255],
    },

    pro: {
      label: 'PRO',
      accent: [17, 19, 23],
      soft: [247, 247, 248],
    },

    study: {
      label: 'STUDY',
      accent: [128, 87, 216],
      soft: [248, 245, 255],
    },

    health: {
      label: 'HEALTH',
      accent: [78, 186, 134],
      soft: [242, 251, 247],
    },
  }

  return styles[universe] || styles.personal
}

export async function exportNoteToPdf({
  note,
  ciriloId,
}) {
  if (!note) return

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth =
    pdf.internal.pageSize.getWidth()

  const pageHeight =
    pdf.internal.pageSize.getHeight()

  const left = 18
  const right = 18
  const top = 18
  const bottom = 24

  const contentWidth =
    pageWidth - left - right

  const universeStyle =
    getUniverseStyle(note.universe)

  const items =
    Array.isArray(note.items)
      ? note.items
      : []

  let logoDataUrl = null

  try {
    logoDataUrl =
      await loadImageAsDataUrl('/logo.png')
  } catch (error) {
    console.warn(
      'Cirilo PDF logo unavailable:',
      error
    )
  }

  let y = top

  // -----------------------------------------
  // HEADER
  // -----------------------------------------

  const drawHeader = (
    firstPage = false
  ) => {
    if (logoDataUrl) {
      try {
        pdf.addImage(
          logoDataUrl,
          'PNG',
          left,
          13,
          32,
          10,
          undefined,
          'FAST'
        )
      } catch (error) {
        console.warn(
          'Could not draw logo:',
          error
        )
      }
    } else {
      pdf.setFont(
        'helvetica',
        'bold'
      )

      pdf.setFontSize(13)

      pdf.setTextColor(
        17,
        19,
        23
      )

      pdf.text(
        'cirilo',
        left,
        20
      )
    }

    const badgeWidth = 27

    pdf.setFillColor(
      ...universeStyle.soft
    )

    pdf.roundedRect(
      pageWidth -
        right -
        badgeWidth,
      13.5,
      badgeWidth,
      8,
      4,
      4,
      'F'
    )

    pdf.setFont(
      'helvetica',
      'bold'
    )

    pdf.setFontSize(7)

    pdf.setTextColor(
      ...universeStyle.accent
    )

    pdf.text(
      universeStyle.label,
      pageWidth -
        right -
        badgeWidth / 2,
      18.7,
      {
        align: 'center',
      }
    )

    if (!firstPage) {
      pdf.setDrawColor(
        238,
        239,
        241
      )

      pdf.line(
        left,
        27,
        pageWidth - right,
        27
      )

      y = 34
    }
  }

  // -----------------------------------------
  // FOOTER
  // -----------------------------------------

  const drawFooter = () => {
    const pageNumber =
      pdf.internal
        .getCurrentPageInfo()
        .pageNumber

    pdf.setDrawColor(
      232,
      234,
      236
    )

    pdf.line(
      left,
      pageHeight - 15,
      pageWidth - right,
      pageHeight - 15
    )

    pdf.setFont(
      'helvetica',
      'normal'
    )

    pdf.setFontSize(7.5)

    pdf.setTextColor(
      145,
      150,
      156
    )

    pdf.text(
      `Generated by ${
        ciriloId ||
        'Cirilo user'
      } on www.cirilo.fr`,
      left,
      pageHeight - 9
    )

    pdf.text(
      String(pageNumber),
      pageWidth - right,
      pageHeight - 9,
      {
        align: 'right',
      }
    )
  }

  // -----------------------------------------
  // PAGE BREAK
  // -----------------------------------------

  const ensureSpace = (
    needed = 10
  ) => {
    if (
      y + needed <=
      pageHeight - bottom
    ) {
      return
    }

    drawFooter()

    pdf.addPage()

    drawHeader(false)
  }

  // -----------------------------------------
  // PARAGRAPH
  // -----------------------------------------

  const addParagraph = (
    text,
    {
      size = 10.2,
      color = [65, 70, 75],
      indent = 0,
      gap = 4,
      style = 'normal',
      lineHeight = 5.2,
    } = {}
  ) => {
    pdf.setFont(
      'helvetica',
      style
    )

    pdf.setFontSize(size)

    pdf.setTextColor(
      ...color
    )

    const lines =
      pdf.splitTextToSize(
        String(text || ''),
        contentWidth - indent
      )

    lines.forEach(
      (line) => {
        ensureSpace(
          lineHeight + 2
        )

        pdf.text(
          line,
          left + indent,
          y
        )

        y += lineHeight
      }
    )

    y += gap
  }

  // -----------------------------------------
  // CHECKLIST ITEM
  // -----------------------------------------

  const drawChecklistItem = (
    item
  ) => {
    const text =
      String(
        item?.text || ''
      ).trim()

    if (!text) return

    const done =
      item.status === 'done'

    const indent = 12

    pdf.setFont(
      'helvetica',
      'normal'
    )

    pdf.setFontSize(10)

    const lines =
      pdf.splitTextToSize(
        text,
        contentWidth - indent
      )

    const itemHeight =
      Math.max(
        12,
        lines.length * 5.2 + 6
      )

    ensureSpace(
      itemHeight + 3
    )

    // Soft card
    pdf.setFillColor(
      250,
      250,
      250
    )

    pdf.setDrawColor(
      235,
      237,
      239
    )

    pdf.roundedRect(
      left,
      y - 5,
      contentWidth,
      itemHeight,
      2.5,
      2.5,
      'FD'
    )

    // Checkbox
    pdf.setDrawColor(
      150,
      155,
      160
    )

    pdf.roundedRect(
      left + 4,
      y - 1.5,
      4,
      4,
      0.6,
      0.6,
      'S'
    )

    // Avoid unicode checkmark
    // because Helvetica PDF
    // may not support it reliably.
    if (done) {
      pdf.setDrawColor(
        ...universeStyle.accent
      )

      pdf.setLineWidth(0.5)

      pdf.line(
        left + 4.8,
        y + 0.3,
        left + 5.8,
        y + 1.3
      )

      pdf.line(
        left + 5.8,
        y + 1.3,
        left + 7.4,
        y - 0.7
      )
    }

    pdf.setFont(
      'helvetica',
      'normal'
    )

    pdf.setFontSize(10)

    pdf.setTextColor(
      ...(done
        ? [145, 150, 156]
        : [48, 52, 57])
    )

    let lineY = y + 1.2

    lines.forEach(
      (line) => {
        pdf.text(
          line,
          left + indent,
          lineY
        )

        lineY += 5.2
      }
    )

    y += itemHeight + 3
  }

  // =========================================
  // FIRST PAGE
  // =========================================

  drawHeader(true)

  y = 35

  pdf.setFont(
    'helvetica',
    'normal'
  )

  pdf.setFontSize(8)

  pdf.setTextColor(
    150,
    155,
    160
  )

  pdf.text(
    'CIRILO NOTE',
    left,
    y
  )

  y += 8

  // -----------------------------------------
  // TITLE
  // -----------------------------------------

  pdf.setFont(
    'helvetica',
    'bold'
  )

  pdf.setFontSize(24)

  pdf.setTextColor(
    20,
    24,
    29
  )

  const titleLines =
    pdf.splitTextToSize(
      String(
        note.title ||
        'Untitled note'
      ),
      contentWidth
    )

  pdf.text(
    titleLines,
    left,
    y
  )

  y +=
    titleLines.length *
      9 +
    4

  // -----------------------------------------
  // ITEM COUNT
  // -----------------------------------------

  const actionableCount =
    items.filter(
      (item) =>
        item.kind !== 'text'
    ).length

  if (
    actionableCount > 0
  ) {
    pdf.setFont(
      'helvetica',
      'normal'
    )

    pdf.setFontSize(8.5)

    pdf.setTextColor(
      145,
      150,
      156
    )

    pdf.text(
      `${actionableCount} ${
        actionableCount === 1
          ? 'item'
          : 'items'
      }`,
      left,
      y
    )

    y += 8
  }

  // -----------------------------------------
  // SEPARATOR
  // -----------------------------------------

  pdf.setDrawColor(
    232,
    234,
    236
  )

  pdf.line(
    left,
    y,
    pageWidth - right,
    y
  )

  y += 10

  // -----------------------------------------
  // CONTENT
  // -----------------------------------------

  if (!items.length) {
    addParagraph(
      'No content.',
      {
        color: [
          145,
          150,
          156,
        ],
      }
    )
  }

  items.forEach(
    (item) => {
      const text =
        String(
          item?.text || ''
        ).trim()

      if (!text) return

      if (
        item.kind === 'text'
      ) {
        addParagraph(
          text,
          {
            size: 10.5,
            lineHeight: 5.7,
            color: [
              72,
              77,
              83,
            ],
            gap: 7,
          }
        )

        return
      }

      drawChecklistItem(
        item
      )
    }
  )

  // -----------------------------------------
  // FINAL FOOTER
  // -----------------------------------------

  drawFooter()

  // -----------------------------------------
  // DOWNLOAD
  // -----------------------------------------

  pdf.save(
    `${safeFilename(
      note.title
    )}.pdf`
  )
}