import { jsPDF } from 'jspdf'

const STATUS_LABELS = {
  new: 'New',
  interview: 'Interview',
  pending: 'Pending',
  hired: 'Hired',
  rejected: 'Rejected',
}

function value(value, fallback = '—') {
  const clean = String(value || '').trim()
  return clean || fallback
}

function anonymizeLastName(lastName) {
  const clean = String(lastName || '').trim()
  if (!clean) return ''
  return `${clean.slice(0, 3).toUpperCase()}***`
}

function safeFileName(value) {
  return String(value || 'talent')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
}

async function loadLogo() {
  try {
    const response = await fetch('/logo.png')
    if (!response.ok) return null
    const blob = await response.blob()

    return await new Promise((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result)
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

function addWrappedText(doc, text, x, y, maxWidth, options = {}) {
  const lines = doc.splitTextToSize(value(text), maxWidth)
  doc.text(lines, x, y, options)
  return y + lines.length * 5
}

function addField(doc, label, content, x, y, width = 75) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(120, 132, 146)
  doc.text(label.toUpperCase(), x, y)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(23, 33, 43)
  const lines = doc.splitTextToSize(value(content), width)
  doc.text(lines, x, y + 6)
  return y + 6 + lines.length * 5
}

function addFooter(doc) {
  const pages = doc.getNumberOfPages()

  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page)
    doc.setDrawColor(226, 232, 238)
    doc.line(20, 282, 190, 282)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(130, 142, 154)
    doc.text('Generated by www.cirilo.fr', 105, 289, {
      align: 'center',
    })
  }
}

function ensureSpace(doc, y, needed = 28) {
  if (y + needed <= 274) return y
  doc.addPage()
  return 24
}

export async function exportTalentPdf(talent, mode = 'client') {
  const clientMode = mode === 'client'
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const logo = await loadLogo()

  if (logo) {
    try {
      doc.addImage(logo, 'PNG', 20, 16, 30, 12, undefined, 'FAST')
    } catch {
      // PDF still works if the logo file is unavailable or not a PNG.
    }
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(17)
    doc.setTextColor(47, 128, 237)
    doc.text('Cirilo', 20, 25)
  }

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(130, 142, 154)
  doc.text(
    clientMode ? 'CANDIDATE PROFILE' : 'TALENT PROFILE',
    190,
    23,
    { align: 'right' }
  )

  doc.setDrawColor(225, 232, 239)
  doc.line(20, 34, 190, 34)

  const firstName = value(talent?.firstName, '')
  const lastName = clientMode
    ? anonymizeLastName(talent?.lastName)
    : value(talent?.lastName, '')

  const displayName =
    [firstName, lastName].filter(Boolean).join(' ') || 'Talent'

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(23, 33, 43)
  doc.text(displayName, 20, 48)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(95, 108, 122)
  doc.text(value(talent?.jobTitle, 'Candidate'), 20, 56)

  let y = 72

  if (clientMode) {
    addField(doc, 'Location', talent?.location, 20, y, 75)
    addField(doc, 'Availability', talent?.availability, 110, y, 75)
    y += 24
    addField(
      doc,
      'Status',
      STATUS_LABELS[talent?.status] || talent?.status,
      20,
      y,
      75
    )

    y += 27
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(120, 132, 146)
    doc.text('PROFILE / COMMENT', 20, y)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(23, 33, 43)
    y = addWrappedText(
      doc,
      talent?.clientComment,
      20,
      y + 7,
      170
    )
  } else {
    addField(doc, 'Location', talent?.location, 20, y, 75)
    addField(doc, 'Availability', talent?.availability, 110, y, 75)
    y += 24

    addField(doc, 'Phone', talent?.phone, 20, y, 75)
    addField(doc, 'Email', talent?.email, 110, y, 75)
    y += 24

    addField(doc, 'Source', talent?.source, 20, y, 75)
    addField(doc, 'Salary / Rate', talent?.salary, 110, y, 75)
    y += 24

    addField(
      doc,
      'Status',
      STATUS_LABELS[talent?.status] || talent?.status,
      20,
      y,
      75
    )
    y += 27

    y = ensureSpace(doc, y, 45)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(120, 132, 146)
    doc.text('INTERNAL NOTES', 20, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(23, 33, 43)
    y = addWrappedText(doc, talent?.notes, 20, y + 7, 170)

    y = ensureSpace(doc, y + 12, 45)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(120, 132, 146)
    doc.text('CLIENT COMMENT', 20, y + 12)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(23, 33, 43)
    addWrappedText(doc, talent?.clientComment, 20, y + 19, 170)
  }

  addFooter(doc)

  const fileBase = safeFileName(
    `${firstName}-${talent?.lastName || 'talent'}`
  )

  doc.save(
    clientMode
      ? `${fileBase}-client-cirilo.pdf`
      : `${fileBase}-full-cirilo.pdf`
  )
}
