import React,{useState} from 'react'
import { ArrowRight, Eye, EyeOff } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function AuthScreen(){
  const {signInGoogle,signInEmail,signUpEmail,resetPassword}=useAuth()
  const [mode,setMode]=useState('signin'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  async function run(fn){ setBusy(true);setError('');setMessage('');try{await fn()}catch(e){const c=e?.code||'';setError(c.includes('invalid-credential')?'Incorrect email or password.':c.includes('email-already-in-use')?'This email is already in use.':c.includes('weak-password')?'Use at least 6 characters.':c.includes('popup-closed')?'Google sign-in was cancelled.':e?.message||'Something went wrong.')}finally{setBusy(false)}}
  function submit(e){e.preventDefault();mode==='signup'?run(async()=>{await signUpEmail({name,email,password});setMessage('Account created. Verification email sent.')}):run(()=>signInEmail(email,password))}
  return <main className="auth-shell"><section className="auth-brand-panel"><img src="/logo.png" alt="Cirilo" className="auth-logo"/><div className="auth-promise"><span className="eyebrow">Your life, in one week.</span><h1>Plan your week.<br/>Follow what matters.</h1><p>Work, personal life, family, friends, tasks and public events — in one calm place.</p></div><div className="auth-ribbons"><i/><i/><i/><i/><i/></div></section><section className="auth-card-wrap"><div className="auth-card"><span className="eyebrow">{mode==='signup'?'Create account':'Welcome back'}</span><h2>{mode==='signup'?'Start your Cirilo.':'Sign in to Cirilo.'}</h2><button className="google-auth-button" disabled={busy} onClick={()=>run(signInGoogle)}><span className="google-g">G</span> Continue with Google</button><div className="auth-separator"><span>or</span></div><form onSubmit={submit} className="auth-form">{mode==='signup'&&<label className="field">Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label className="field">Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field">Password<div className="password-field"><input type={show?'text':'password'} minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="6+ characters"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></label>{mode==='signin'&&<button type="button" className="auth-link" onClick={()=>{if(!email)return setError('Enter your email first.');run(async()=>{await resetPassword(email);setMessage('Password reset email sent.')})}}>Forgot password?</button>}{error&&<p className="auth-error">{error}</p>}{message&&<p className="auth-success">{message}</p>}<button className="primary-btn auth-submit" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':'Sign in'} {!busy&&<ArrowRight size={16}/>}</button></form><p className="auth-switch">{mode==='signup'?'Already have an account?':'New to Cirilo?'} <button onClick={()=>{setMode(mode==='signup'?'signin':'signup');setError('');setMessage('')}}>{mode==='signup'?'Sign in':'Create an account'}</button></p></div></section></main>
}
